package management

import (
	"net/http"

	"github.com/router-for-me/CLIProxyAPI/v7/sdk/pluginapi"
)

func lookupPage() pluginapi.ManagementResponse {
	return pluginapi.ManagementResponse{
		StatusCode: http.StatusOK,
		Headers: http.Header{
			"Content-Type":  []string{"text/html; charset=utf-8"},
			"Cache-Control": []string{"no-store"},
		},
		Body: []byte(lookupHTML),
	}
}

const lookupHTML = `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Key 自助查询</title>
<script src="https://cdn.jsdelivr.net/npm/echarts@5.6.0/dist/echarts.min.js"></script>
<style>
:root { --bg:#f7f8f5; --panel:#fff; --ink:#26332b; --muted:#758077; --line:#e1e7e2; --accent:#14926b; --accent-dark:#087b57; --accent-soft:#e7f7ef; --warn:#d88a1a; --danger:#c14a41; font-family:Inter,"Noto Sans SC",ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif; }
* { box-sizing:border-box; } body { margin:0; min-height:100vh; background:var(--bg); color:var(--ink); } main { width:min(1440px,calc(100% - 40px)); margin:auto; padding:38px 0 56px; }
.topbar { display:flex; align-items:center; justify-content:space-between; gap:20px; padding:0 2px 22px; border-bottom:1px solid var(--line); } .brand { color:var(--accent-dark); font-size:.75rem; font-weight:800; letter-spacing:.1em; text-transform:uppercase; } h1 { margin:6px 0 0; font-size:1.55rem; letter-spacing:-.04em; } .topbar p { margin:0; color:var(--muted); font-size:.83rem; }.display-controls { display:flex; align-items:center; justify-content:flex-end; gap:8px; flex-wrap:wrap; }.unit-switch { display:inline-flex; align-items:center; overflow:hidden; border:1px solid #dce5de; border-radius:8px; background:#f8faf8; }.unit-switch span { padding:0 8px; color:var(--muted); font-size:.73rem; white-space:nowrap; }.unit-switch button { min-width:34px; padding:7px 8px; border:0; border-left:1px solid #dce5de; border-radius:0; background:#fff; color:var(--ink); box-shadow:none; font-size:.74rem; }.unit-switch button:hover { background:var(--accent-soft); color:var(--accent-dark); }.unit-switch button.active { background:#6c6a62; color:#fff; }.rate-field { display:flex; align-items:center; gap:5px; color:var(--muted); font-size:.72rem; white-space:nowrap; }.rate-field input { width:70px; padding:6px 7px; font-family:inherit; font-size:.74rem; }
.lookup { display:grid; grid-template-columns:minmax(0,1fr) auto; gap:9px; margin:22px 0 8px; padding:7px; border:1px solid var(--line); border-radius:12px; background:var(--panel); box-shadow:0 6px 16px rgba(27,52,38,.04); } input,select { width:100%; min-width:0; border:1px solid #dce5de; border-radius:8px; outline:0; background:#fcfdfb; padding:10px 11px; color:var(--ink); font:inherit; font-size:.86rem; } input { font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; } input:focus,select:focus { border-color:#76d7b8; box-shadow:0 0 0 3px rgba(30,183,135,.12); background:#fff; }
button { border:0; border-radius:8px; padding:10px 16px; background:var(--accent); color:#fff; cursor:pointer; font:inherit; font-size:.86rem; font-weight:700; } button:hover { background:var(--accent-dark); } button:disabled { cursor:wait; opacity:.62; }.privacy { margin:0 2px; color:var(--muted); font-size:.74rem; }.error { margin-top:18px; padding:11px 13px; border:1px solid #efd0cd; border-radius:9px; background:#fff6f5; color:var(--danger); font-size:.85rem; }.hidden { display:none!important; }
.dashboard { margin-top:26px; }.key-head { display:flex; align-items:center; justify-content:space-between; gap:14px; margin-bottom:14px; }.key-head h2 { margin:0; font-size:1.06rem; }.key-head h2::before { content:""; display:inline-block; width:8px; height:8px; margin-right:8px; border-radius:50%; background:var(--accent); }.fingerprint { color:var(--muted); font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:.75rem; }
.section { margin-top:25px; }.section-head { display:flex; align-items:center; justify-content:space-between; gap:12px; margin:0 1px 10px; }.section-head h3 { margin:0; font-size:.95rem; }.section-head span { color:var(--muted); font-size:.75rem; }.quota-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:12px; }.quota-card { padding:15px; border:1px solid var(--line); border-radius:11px; background:var(--panel); }.quota-card.wide { grid-column:span 2; }.quota-top { display:flex; align-items:baseline; justify-content:space-between; gap:10px; }.quota-name { color:var(--muted); font-size:.78rem; }.quota-value { font-size:.88rem; font-weight:750; }.quota-detail { margin-top:6px; color:var(--muted); font-size:.73rem; }.progress { height:8px; margin-top:13px; overflow:hidden; border-radius:99px; background:#edf1ee; }.progress i { display:block; height:100%; min-width:0; border-radius:inherit; background:var(--accent); }.progress.warn i { background:var(--warn); }.progress.danger i { background:var(--danger); }.unlimited { color:var(--muted); font-size:.76rem; }
.filter-panel { padding:14px; border:1px solid var(--line); border-radius:11px; background:var(--panel); }.filter-bar { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:10px; align-items:end; }.filter-bar:has(.custom-range:not(.hidden)) { grid-template-columns:repeat(5,minmax(0,1fr)); }.filter-bar button { min-width:0; width:100%; padding:10px 18px; }.custom-range { display:contents; }.custom-range.hidden { display:none; }.date-field { position:relative; }.custom-range input { position:relative; z-index:1; font-family:inherit; background:transparent; }.date-placeholder { position:absolute; z-index:0; top:50%; left:12px; transform:translateY(-50%); color:var(--muted); font-size:.86rem; pointer-events:none; }.date-field.has-value .date-placeholder { display:none; }.stats { display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:10px; margin-top:12px; }.stat { padding:14px; border:1px solid var(--line); border-radius:10px; background:var(--panel); }.stat .label { color:var(--muted); font-size:.73rem; }.stat .value { margin-top:7px; font-size:1.28rem; font-weight:780; letter-spacing:-.04em; }
.analytics { display:grid; grid-template-columns:minmax(0,1.65fr) minmax(350px,.72fr); gap:14px; align-items:stretch; }.trend-stack { display:grid; grid-template-rows:repeat(2,minmax(278px,1fr)); gap:14px; min-width:0; }.chart-card { min-width:0; padding:15px; border:1px solid var(--line); border-radius:11px; background:var(--panel); overflow:hidden; }.chart-card .section-head { margin:0 0 8px; }.analytics .share-card { display:flex; flex-direction:column; min-height:570px; }.chart { width:100%; height:214px; }.share-card .chart { flex:1; min-height:335px; }.share-legend { display:grid; gap:7px; margin:3px 4px 0; max-height:140px; overflow-y:auto; }.share-legend-item { display:flex; align-items:center; gap:7px; min-width:0; color:#4d5a51; font-size:.76rem; }.share-legend-dot { flex:0 0 8px; width:8px; height:8px; border-radius:2px; }.share-legend-name { min-width:0; flex:1; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-weight:650; }.share-legend-value { flex:0 0 auto; color:var(--muted); font-weight:700; }.chart-legend { display:flex; flex-wrap:wrap; gap:12px; margin-top:3px; color:var(--muted); font-size:.71rem; }.chart-legend i { display:inline-block; width:7px; height:7px; margin-right:4px; border-radius:50%; }.chart-empty { display:grid; min-height:190px; place-items:center; color:var(--muted); font-size:.82rem; }.metric-switch { display:inline-flex; overflow:hidden; border:1px solid #dce5de; border-radius:7px; background:#f7faf7; }.metric-switch button { padding:5px 8px; border-radius:0; background:transparent; color:var(--muted); box-shadow:none; font-size:.72rem; font-weight:650; }.metric-switch button + button { border-left:1px solid #dce5de; }.metric-switch button.active { background:#6c6a62; color:#fff; }
.table-wrap { overflow:auto; border:1px solid var(--line); border-radius:11px; background:var(--panel); }table { width:100%; min-width:650px; border-collapse:collapse; font-size:.83rem; }th,td { padding:12px 13px; border-bottom:1px solid #edf0ed; text-align:left; }th { color:var(--muted); background:#fafcf9; font-size:.72rem; font-weight:700; white-space:nowrap; }tbody tr:last-child td { border-bottom:0; }td.model { max-width:250px; overflow:hidden; font-weight:650; text-overflow:ellipsis; white-space:nowrap; }.empty { padding:28px; color:var(--muted); font-size:.83rem; text-align:center; }.recent-pagination { display:flex; align-items:center; gap:12px; margin-top:10px; padding:10px 12px; border:1px solid var(--line); border-radius:10px; background:var(--panel); color:var(--muted); font-size:.78rem; }.recent-pagination .page-meta { display:flex; align-items:center; justify-content:space-between; flex:1 1 auto; gap:12px; min-width:0; }.recent-pagination .page-summary { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }.recent-pagination label { display:flex; align-items:center; gap:6px; white-space:nowrap; }.recent-pagination select { width:auto; min-width:82px; padding:7px 25px 7px 8px; font-size:.78rem; }.page-nav { display:grid; grid-template-columns:auto auto auto; align-items:center; gap:8px; white-space:nowrap; }.recent-pagination button { padding:7px 11px; border:1px solid #dce5de; border-radius:7px; background:#fff; color:var(--ink); box-shadow:none; font-size:.78rem; }.recent-pagination button:hover:not(:disabled) { border-color:#9ad7bf; background:var(--accent-soft); color:var(--accent-dark); }.recent-pagination button:disabled { border-color:#e6ebe7; background:#f5f7f5; color:#a4ada6; }
@media (max-width:720px) { main { width:min(100% - 24px,1440px); padding-top:25px; }.topbar { align-items:flex-start; flex-direction:column; gap:10px; }.display-controls { width:100%; justify-content:flex-start; }.lookup,.filter-bar,.filter-bar:has(.custom-range:not(.hidden)) { grid-template-columns:1fr; }.lookup button,.filter-bar button { width:100%; }.custom-range { display:contents; }.quota-grid,.stats { grid-template-columns:repeat(2,minmax(0,1fr)); }.quota-card.wide { grid-column:span 2; }.analytics { grid-template-columns:1fr; }.trend-stack { grid-template-rows:none; }.analytics .share-card { min-height:410px; }.chart,.share-card .chart { height:250px; min-height:250px; }.recent-pagination { display:grid; grid-template-columns:1fr; gap:10px; }.recent-pagination .page-meta { width:100%; }.page-nav { grid-template-columns:minmax(0,1fr) auto minmax(0,1fr); width:100%; }.page-nav button { width:100%; }.key-head { align-items:flex-start; flex-direction:column; gap:5px; } }
</style>
</head>
<body>
<main>
  <header class="topbar"><div><div class="brand">Credit Manager</div><h1>Key 额度与使用统计</h1></div><div class="display-controls"><div class="unit-switch" id="tokenUnitSwitch" role="group" aria-label="Token 显示单位"><span>Token</span><button type="button" data-token-unit="raw" title="原始数量">个</button><button type="button" data-token-unit="k" title="千 (×1,000)">千</button><button type="button" data-token-unit="w" title="万 (×10,000)">万</button><button type="button" data-token-unit="m" title="百万 (×1,000,000)">百万</button></div><div class="unit-switch" id="currencySwitch" role="group" aria-label="费用显示货币"><span>费用</span><button type="button" data-currency="USD">USD</button><button type="button" data-currency="CNY">CNY</button></div><label class="rate-field hidden" id="usdCnyRateField">1 USD = <input id="usdCnyRate" type="number" step="0.0001" min="0.0001" inputmode="decimal" aria-label="美元兑人民币汇率"/> CNY</label><p>输入 Key 后仅可查看该 Key 自身的数据</p></div></header>
  <form class="lookup" id="lookupForm"><input id="key" type="password" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="粘贴 tk- 开头的 Key" aria-label="插件 Key" required/><button id="submit" type="submit">查询</button></form>
  <p class="privacy">Key 仅用于本次请求，不会保存到页面、浏览器或地址栏。</p><div id="error" class="error hidden" role="alert"></div>
  <section id="dashboard" class="dashboard hidden">
    <div class="key-head"><h2 id="keyLabel">Key 概览</h2><span id="fingerprint" class="fingerprint"></span></div>
    <div class="section"><div class="section-head"><h3>额度使用</h3><span>含当前在途预占</span></div><div id="quotas" class="quota-grid"></div></div>
    <div class="section"><div class="section-head"><h3>使用统计</h3></div><div class="filter-panel"><div class="filter-bar"><select id="range" aria-label="时间范围"><option value="today">今日</option><option value="7">最近 7 天</option><option value="30" selected>最近 30 天</option><option value="90">最近 90 天</option><option value="custom">自定义范围</option><option value="all">全部时间</option></select><div id="customRange" class="custom-range hidden"><span class="date-field" id="fromField"><input id="from" type="date" aria-label="开始时间（UTC）" title="开始时间（UTC）"/><span class="date-placeholder">开始时间</span></span><span class="date-field" id="toField"><input id="to" type="date" aria-label="结束时间（UTC）" title="结束时间（UTC）"/><span class="date-placeholder">结束时间</span></span></div><select id="model" aria-label="模型"><option value="">全部模型</option></select><button id="refresh" type="button">刷新统计</button></div></div><div id="stats" class="stats"></div></div>
    <div class="section"><div class="analytics"><div class="trend-stack"><div class="chart-card"><div class="section-head"><h3>Token 趋势</h3><span id="tokenTrendTotal">—</span></div><div class="chart-legend"><span><i style="background:#14926b"></i>输入</span><span><i style="background:#7565ef"></i>输出</span><span><i style="background:#e89a36"></i>缓存读取</span><span><i style="background:#e56b8a"></i>缓存命中率</span></div><div id="tokenTrend" class="chart" aria-label="Token 趋势图"></div></div><div class="chart-card"><div class="section-head"><h3>费用趋势</h3><span id="costTrendTotal">—</span></div><div class="chart-legend"><span><i style="background:#14926b"></i>费用</span></div><div id="costTrend" class="chart" aria-label="费用趋势图"></div></div></div><div class="chart-card share-card"><div class="section-head"><h3>模型调用占比</h3><div class="metric-switch" id="modelMetric"><button type="button" data-metric="requests" class="active">调用次数</button><button type="button" data-metric="tokens">Token</button><button type="button" data-metric="cost">费用</button></div></div><div id="modelShare" class="chart" aria-label="模型调用占比图"></div><div id="modelShareLegend" class="share-legend"></div></div></div></div>
    <div class="section"><div class="section-head"><h3>最近调用</h3><span id="recentState">—</span></div><div id="recent" class="table-wrap"></div><div id="recentPagination" class="recent-pagination"></div></div>
  </section>
</main>
<script>
(() => {
  const $ = id => document.getElementById(id), endpoint = location.pathname.replace(/\/lookup\/?$/, '/lookup/data'); let token = '', data = null, modelMetric = 'requests', recentPage = 1, recentPageSize = 25; const charts = {};
  const TOKEN_UNITS={raw:{div:1,suffix:'',maxFrac:0},k:{div:1e3,suffix:'千',maxFrac:2},w:{div:1e4,suffix:'万',maxFrac:2},m:{div:1e6,suffix:'百万',maxFrac:2}}, TOKEN_UNIT_KEY='credit-manager.token-unit', CURRENCY_KEY='credit-manager.currency', USD_CNY_RATE_KEY='credit-manager.usd-cny-rate', DEFAULT_USD_CNY_RATE=7.2;
  let tokenUnit=TOKEN_UNITS[localStorage.getItem(TOKEN_UNIT_KEY)]?localStorage.getItem(TOKEN_UNIT_KEY):'raw', currency=localStorage.getItem(CURRENCY_KEY)==='CNY'?'CNY':'USD', usdCnyRate=Math.max(0.0001,Number(localStorage.getItem(USD_CNY_RATE_KEY))||DEFAULT_USD_CNY_RATE);
  const count = value => { const n=Number(value); return Number.isFinite(n)?Math.round(n).toLocaleString():'—'; }, tokens = value => { const n=Number(value); if(!Number.isFinite(n))return '—'; const unit=TOKEN_UNITS[tokenUnit], scaled=n/unit.div, abs=Math.abs(scaled), maxFrac=abs>0&&abs<.01?6:(abs>=100?1:unit.maxFrac); return scaled.toLocaleString(undefined,{maximumFractionDigits:maxFrac})+unit.suffix; }, tokenValue = value => tokens(value)+' Token', money = value => { const usd=Number(value||0)/1e6; if(currency==='CNY') { const abs=Math.abs(usd*usdCnyRate), maxFrac=abs>=100?2:(abs>=1?3:4); return '¥'+(usd*usdCnyRate).toLocaleString(undefined,{maximumFractionDigits:maxFrac}); } return '$'+usd.toLocaleString(undefined,{maximumFractionDigits:6}); }, usd = value => money(value)+' '+currency, esc = v => String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  function syncDisplayControls() { document.querySelectorAll('#tokenUnitSwitch [data-token-unit]').forEach(button=>button.classList.toggle('active',button.dataset.tokenUnit===tokenUnit)); document.querySelectorAll('#currencySwitch [data-currency]').forEach(button=>button.classList.toggle('active',button.dataset.currency===currency)); $('usdCnyRateField').classList.toggle('hidden',currency!=='CNY'); if(document.activeElement!==$('usdCnyRate')) $('usdCnyRate').value=String(usdCnyRate); }
  function refreshDisplayUnits() { if(data) { render(data); renderRecentPagination(data.recent_pagination); } }
  const totalTokens = item => Number(item.input_tokens||0)+Number(item.output_tokens||0);
  function syncDatePlaceholder(id) { $(id+'Field').classList.toggle('has-value',Boolean($(id).value)); }
  function syncCustomRange() { $('customRange').classList.toggle('hidden',$('range').value!=='custom'); syncDatePlaceholder('from'); syncDatePlaceholder('to'); }
  function rangeQuery() { const value = $('range').value; if (value === 'all') return ''; if (value === 'custom') { const from=$('from').value, to=$('to').value; if (!from || !to) throw new Error('请选择自定义范围的开始和结束日期'); if (from>to) throw new Error('开始日期不能晚于结束日期'); return 'from='+encodeURIComponent(from+'T00:00:00.000Z')+'&to='+encodeURIComponent(to+'T23:59:59.999Z'); } const now = new Date(), from = new Date(now); if (value === 'today') from.setUTCHours(0,0,0,0); else from.setUTCDate(now.getUTCDate()-Number(value)+1); from.setUTCHours(0,0,0,0); return 'from='+encodeURIComponent(from.toISOString())+'&to='+encodeURIComponent(now.toISOString()); }
  function quota(name, used, maximum, detail, wide=false) { if (!Number(maximum||0)) return '<div class="quota-card '+(wide?'wide':'')+'"><div class="quota-top"><span class="quota-name">'+esc(name)+'</span><span class="unlimited">不限制</span></div><div class="quota-detail">已用 '+money(used)+' · '+esc(detail)+'</div><div class="progress"><i style="width:0%"></i></div></div>'; const percent = Math.min(100,Math.max(0,Number(used)/Number(maximum)*100)), tone = percent>=90?'danger':percent>=70?'warn':''; return '<div class="quota-card '+(wide?'wide ':'')+'"><div class="quota-top"><span class="quota-name">'+esc(name)+'</span><span class="quota-value">'+money(used)+' / '+money(maximum)+'</span></div><div class="quota-detail">剩余 '+money(Math.max(0,Number(maximum)-Number(used)))+' · '+percent.toFixed(1)+'%</div><div class="progress '+tone+'"><i style="width:'+percent+'%"></i></div></div>'; }
  function concurrent(active, maximum) { if (!Number(maximum||0)) return '<div class="quota-card"><div class="quota-top"><span class="quota-name">最大并发</span><span class="unlimited">不限制</span></div><div class="quota-detail">当前在途 '+count(active)+' 个请求</div><div class="progress"><i style="width:0%"></i></div></div>'; const p=Math.min(100,Number(active)/Number(maximum)*100), tone=p>=90?'danger':p>=70?'warn':''; return '<div class="quota-card"><div class="quota-top"><span class="quota-name">最大并发</span><span class="quota-value">'+count(active)+' / '+count(maximum)+'</span></div><div class="quota-detail">当前在途请求数</div><div class="progress '+tone+'"><i style="width:'+p+'%"></i></div></div>'; }
  function table(headers, rows) { return rows.length?'<table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table>':'<div class="empty">当前筛选条件下暂无数据</div>'; }
  function duration(value) { if(value==null||value==='')return '—'; const n=Number(value);return Number.isFinite(n)?(n<1000?(n<100?n.toFixed(1):n.toFixed(0))+' ms':(n/1000).toFixed(2)+' s'):'—'; }
  function tps(value) { const n=Number(value); return Number.isFinite(n)?n.toFixed(2):'—'; }
  function allTokens(item) { const reported=Number(item.total_tokens||0); if(reported>0) return reported; const total=Number(item.input_tokens||0)+Number(item.output_tokens||0)+Number(item.reasoning_tokens||0); return total>0?total:Number(item.cached_tokens||0); }
  const palette=['#7968ee','#1eb787','#f0a04b','#e56b8a','#4dabf7','#20c997','#ff922b','#cc5de8'];
  function destroyChart(id) { if(charts[id]) charts[id].dispose(); delete charts[id]; }
  function chart(id, empty, option) { const target=$(id); destroyChart(id); if(!option||!window.echarts) { target.className='chart chart-empty'; target.textContent=window.echarts?empty:'图表组件加载失败'; return; } target.className='chart'; target.textContent=''; const instance=echarts.init(target,null,{renderer:'svg'}); instance.setOption(option); charts[id]=instance; }
  function lineChart(id, points, series, empty, moneyAxis=false) { if(!points.length) return chart(id,empty,null); const right=series.some(x=>x.right), allZero=series.every(s=>points.every(x=>Number(x[s.key]||0)===0)); chart(id,empty,{color:series.map(x=>x.color),animationDuration:360,grid:{top:32,right:right?52:18,bottom:30,left:66},legend:{top:0,left:0,itemWidth:11,itemHeight:3,itemGap:14,textStyle:{color:'#4f5b53',fontSize:11,fontWeight:600}},tooltip:{trigger:'axis',backgroundColor:'rgba(26,31,28,.94)',borderWidth:0,padding:[9,11],textStyle:{color:'#fff',fontSize:12},axisPointer:{type:'line',lineStyle:{color:'#9ea9a1',type:'dashed'}},formatter:params=>'<strong>'+esc(params[0].axisValue)+'</strong><br/>'+params.map(param=>param.marker+series[param.seriesIndex].name+' <b style="float:right;margin-left:18px">'+series[param.seriesIndex].format(param.value)+'</b>').join('<br/>')},xAxis:{type:'category',boundaryGap:false,data:points.map(x=>x.date),axisLine:{lineStyle:{color:'#dce5de'}},axisTick:{show:false},axisLabel:{color:'#6a766e',fontSize:10,formatter:v=>v.slice(5)}},yAxis:[{type:'value',min:0,max:allZero?1:null,splitNumber:3,axisLabel:{color:'#6a766e',fontSize:10,formatter:v=>moneyAxis?(allZero?'$0 USD':usd(v)):tokenValue(v)},splitLine:{lineStyle:{color:'#e8eeea'}},axisLine:{show:false},axisTick:{show:false}},...(right?[{type:'value',min:0,max:100,splitNumber:2,axisLabel:{color:'#6a766e',fontSize:10,formatter:v=>v.toFixed(0)+'%'},splitLine:{show:false},axisLine:{show:false},axisTick:{show:false}}]:[])],series:series.map(s=>({name:s.name,type:'line',smooth:true,showSymbol:points.length<=31,symbol:'circle',symbolSize:6,yAxisIndex:s.right?1:0,lineStyle:{width:s.dashed?2:2.5,type:s.dashed?'dashed':'solid'},itemStyle:{borderWidth:2,borderColor:'#fff'},areaStyle:s.fill?{color:s.fill}:undefined,data:points.map(x=>Number(x[s.key]||0))}))}); }
  function shareMetricValue(item) { if(modelMetric==='tokens')return Number(item.total_tokens||0); if(modelMetric==='cost')return Number(item.cost_micro_usd||0); return Number(item.request_count||0); }
  function shareMetricLabel() { return modelMetric==='tokens'?'Token':modelMetric==='cost'?'费用':'请求次数'; }
  function shareMetricFormat(value) { return modelMetric==='tokens'?tokenValue(value):modelMetric==='cost'?usd(value):count(value)+' 请求'; }
  function renderModelShare(models) { const sorted=[...models].sort((a,b)=>shareMetricValue(b)-shareMetricValue(a)), total=sorted.reduce((sum,x)=>sum+shareMetricValue(x),0), legend=$('modelShareLegend'); document.querySelectorAll('#modelMetric [data-metric]').forEach(button=>button.classList.toggle('active',button.dataset.metric===modelMetric)); if(!sorted.length||!total) { legend.innerHTML=''; return chart('modelShare','当前筛选条件下暂无模型使用数据',null); } legend.innerHTML=sorted.map((item,index)=>'<div class="share-legend-item" title="'+esc(item.model)+'"><i class="share-legend-dot" style="background:'+palette[index%palette.length]+'"></i><span class="share-legend-name">'+esc(item.model)+'</span><span class="share-legend-value">'+(shareMetricValue(item)/total*100).toFixed(1)+'%</span></div>').join(''); chart('modelShare','当前筛选条件下暂无模型使用数据',{color:sorted.map((_,i)=>palette[i%palette.length]),animationDuration:360,tooltip:{trigger:'item',backgroundColor:'rgba(26,31,28,.94)',borderWidth:0,padding:[9,11],textStyle:{color:'#fff',fontSize:12},formatter:param=>'<strong>'+esc(param.data.item.model)+'</strong><br/>'+esc(shareMetricLabel())+' <b style="float:right;margin-left:18px">'+esc(shareMetricFormat(param.value))+'</b><br/>占比 <b style="float:right;margin-left:18px">'+param.percent.toFixed(1)+'%</b>'},series:[{name:shareMetricLabel(),type:'pie',radius:['42%','60%'],center:['50%','50%'],minAngle:3,itemStyle:{borderColor:'#fff',borderWidth:3,borderRadius:4},label:{show:true,position:'center',formatter:'{total|'+shareMetricFormat(total)+'}\n{caption|'+shareMetricLabel()+'}',rich:{total:{color:'#1f2922',fontSize:22,fontWeight:700,lineHeight:28},caption:{color:'#5f6a61',fontSize:11,fontWeight:600,lineHeight:17}}},labelLine:{show:false},emphasis:{scale:true,scaleSize:7},data:sorted.map(item=>({name:item.model,value:shareMetricValue(item),item}))}]}); }
  function renderCharts(result) { const points=(result.daily_trend||[]).map(point=>({...point,cache_hit_rate:(Number(point.cached_tokens||0)+Number(point.cache_read_tokens||0)+Number(point.cache_creation_tokens||0))>0?Number(point.cache_read_tokens||0)/(Number(point.cached_tokens||0)+Number(point.cache_read_tokens||0)+Number(point.cache_creation_tokens||0))*100:0})), models=result.by_model||[], input=points.reduce((sum,p)=>sum+Number(p.input_tokens||0),0),output=points.reduce((sum,p)=>sum+Number(p.output_tokens||0),0),cache=points.reduce((sum,p)=>sum+Number(p.cache_read_tokens||0),0),related=points.reduce((sum,p)=>sum+Number(p.cached_tokens||0)+Number(p.cache_read_tokens||0)+Number(p.cache_creation_tokens||0),0); $('tokenTrendTotal').textContent=points.length?'入 '+tokenValue(input)+' · 出 '+tokenValue(output)+' · 缓存 '+tokenValue(cache)+(related?' · 命中 '+(cache/related*100).toFixed(1)+'%':''):'—'; $('costTrendTotal').textContent=points.length?usd(points.reduce((sum,p)=>sum+Number(p.cost_micro_usd||0),0)):'—'; lineChart('tokenTrend',points,[{key:'input_tokens',name:'输入',color:'#1eb787',format:tokenValue},{key:'output_tokens',name:'输出',color:'#7968ee',format:tokenValue},{key:'cache_read_tokens',name:'缓存读取',color:'#f0a04b',format:tokenValue},{key:'cache_hit_rate',name:'缓存命中率',color:'#e56b8a',right:true,dashed:true,format:v=>Number(v).toFixed(1)+'%'}],'当前筛选条件下暂无 Token 趋势'); lineChart('costTrend',points,[{key:'cost_micro_usd',name:'费用',color:'#1eb787',fill:true,format:usd}],'当前筛选条件下暂无费用趋势',true); renderModelShare(models); }
  function renderRecentPagination(pagination) { const p=pagination||{}, page=Number(p.page||1), size=Number(p.page_size||recentPageSize), total=Number(p.total||0), pages=Math.max(Number(p.total_pages||0),1), start=total?(page-1)*size+1:0, end=Math.min(page*size,total); recentPage=page; recentPageSize=size; const summary='显示 '+count(start)+'–'+count(end)+'，共 '+count(total)+' 条'; $('recentState').textContent=summary; $('recentPagination').innerHTML='<div class="page-meta"><span class="page-summary">'+summary+'</span><label>每页 <select id="recentPageSize"><option value="25">25 条</option><option value="50">50 条</option><option value="100">100 条</option><option value="200">200 条</option></select></label></div><div class="page-nav"><button type="button" id="recentPrev" '+(page<=1?'disabled':'')+'>上一页</button><span>第 '+count(page)+' / '+count(pages)+' 页</span><button type="button" id="recentNext" '+(page>=pages?'disabled':'')+'>下一页</button></div>'; $('recentPageSize').value=String(size); $('recentPageSize').addEventListener('change',event=>{recentPageSize=Number(event.target.value);recentPage=1;load(false,false,true)}); $('recentPrev').addEventListener('click',()=>{recentPage=Math.max(1,page-1);load(false,false,true)}); $('recentNext').addEventListener('click',()=>{recentPage=Math.min(pages,page+1);load(false,false,true)}); }
  function render(result) { data=result; const key=result.key, overview=result.overview, summary=result.usage_summary||{}, models=result.by_model||[]; $('keyLabel').textContent=key.label||'我的 Key'; $('fingerprint').textContent='指纹 '+(key.fingerprint||'—'); $('quotas').innerHTML=[quota('总额度',Number(key.settled_spend_micro_usd||0)+Number(key.held_amount_micro_usd||0),key.quota_micro_usd,'累计已结算与在途预占',true),quota('日额度',overview.daily_micro_usd,key.daily_quota_micro_usd,'UTC 自然日'),quota('周额度',overview.weekly_micro_usd,key.weekly_quota_micro_usd,'UTC 周一开始'),quota('月额度',overview.monthly_micro_usd,key.monthly_quota_micro_usd,'UTC 自然月'),concurrent(overview.active_reservations,key.max_concurrent_requests)].join(''); $('stats').innerHTML=[['请求数',count(summary.request_count)+' 请求'],['Token',tokenValue(Number(summary.total_tokens||0)||(Number(summary.input_tokens||0)+Number(summary.output_tokens||0)+Number(summary.reasoning_tokens||0)))],['费用',usd(summary.cost_micro_usd)],['在途请求',count(overview.active_reservations)+' 请求']].map(x=>'<div class="stat"><div class="label">'+x[0]+'</div><div class="value">'+x[1]+'</div></div>').join(''); const modelSelect=$('model'), current=modelSelect.value; modelSelect.innerHTML='<option value="">全部模型</option>'+models.map(x=>'<option value="'+esc(x.model)+'">'+esc(x.model)+'</option>').join(''); if ([...modelSelect.options].some(x=>x.value===current)) modelSelect.value=current; $('recent').innerHTML=table(['时间','模型名称','来源','结果','首字延迟','生成时间','TPS','思考强度','输入 Token','输出 Token','思考 Token','缓存读取 Token','缓存创建 Token','总 Token 数','缓存命中','费用'],(result.recent_usage||[]).map(x=>'<tr><td>'+esc(new Date(x.created_at).toLocaleString())+'</td><td class="model" title="'+esc(x.model)+'">'+esc(x.model)+'</td><td>'+esc(x.source||'—')+'</td><td>'+esc(x.result||'—')+'</td><td>'+esc(duration(x.first_token_latency_ms))+'</td><td>'+esc(duration(x.generation_duration_ms))+'</td><td>'+esc(tps(x.tokens_per_second))+'</td><td>'+esc(x.thinking_intensity||'—')+'</td><td>'+tokenValue(x.input_tokens)+'</td><td>'+tokenValue(x.output_tokens)+'</td><td>'+tokenValue(x.reasoning_tokens)+'</td><td>'+tokenValue(x.cache_read_tokens)+'</td><td>'+tokenValue(x.cache_creation_tokens)+'</td><td>'+tokenValue(allTokens(x))+'</td><td>'+esc(Number(x.cache_read_tokens||0)>0?'是':'否')+'</td><td>'+usd(x.cost_micro_usd)+'</td></tr>')); $('dashboard').classList.remove('hidden'); renderCharts(result); }
  function normalizeKey(value) { return String(value||'').replace(/[\s\u200B-\u200D\uFEFF]/g,''); }
  function validateKey(value) { if(!value) return '请输入 Key。'; if(!/^[\x20-\x7E]+$/.test(value)) return 'Key 包含非英文字符或不可见字符，请重新复制完整的 tk- 开头 Key。'; if(!/^tk-[A-Za-z0-9-]+$/.test(value)) return 'Key 格式不正确，请输入 tk- 开头的完整 Key。'; return ''; }
  async function load(isNew=false, resetPage=false, recentOnly=false) { const error=$('error'), button=isNew?$('submit'):$('refresh'); error.classList.add('hidden'); if(isNew){ token=normalizeKey($('key').value); $('key').value=token; $('dashboard').classList.add('hidden'); const validation=validateKey(token); if(validation) { error.textContent=validation; error.classList.remove('hidden'); return; } } if(resetPage||isNew) recentPage=1; if(!token) return; button.disabled=true; button.textContent='加载中…'; try { const q=[rangeQuery(),$('model').value?'model='+encodeURIComponent($('model').value):'', 'page='+recentPage, 'page_size='+recentPageSize, recentOnly?'recent_only=1':''].filter(Boolean).join('&'); const response=await fetch(endpoint+(q?'?'+q:''),{headers:{Authorization:'Bearer '+token},cache:'no-store'}), result=await response.json(); if(!response.ok) throw new Error(result.error||'查询失败，请检查 Key。'); if(recentOnly) { $('recent').innerHTML=table(['时间','模型名称','来源','结果','首字延迟','生成时间','TPS','思考强度','输入 Token','输出 Token','思考 Token','缓存读取 Token','缓存创建 Token','总 Token 数','缓存命中','费用'],(result.recent_usage||[]).map(x=>'<tr><td>'+esc(new Date(x.created_at).toLocaleString())+'</td><td class="model" title="'+esc(x.model)+'">'+esc(x.model)+'</td><td>'+esc(x.source||'—')+'</td><td>'+esc(x.result||'—')+'</td><td>'+esc(duration(x.first_token_latency_ms))+'</td><td>'+esc(duration(x.generation_duration_ms))+'</td><td>'+esc(tps(x.tokens_per_second))+'</td><td>'+esc(x.thinking_intensity||'—')+'</td><td>'+tokenValue(x.input_tokens)+'</td><td>'+tokenValue(x.output_tokens)+'</td><td>'+tokenValue(x.reasoning_tokens)+'</td><td>'+tokenValue(x.cache_read_tokens)+'</td><td>'+tokenValue(x.cache_creation_tokens)+'</td><td>'+tokenValue(allTokens(x))+'</td><td>'+esc(Number(x.cache_read_tokens||0)>0?'是':'否')+'</td><td>'+usd(x.cost_micro_usd)+'</td></tr>')); } else { render(result); } renderRecentPagination(result.recent_pagination); } catch(err) { error.textContent=err.message||'查询失败，请稍后重试。'; error.classList.remove('hidden'); } finally { button.disabled=false; button.textContent=isNew?'查询':'刷新统计'; } }
  $('lookupForm').addEventListener('submit',e=>{e.preventDefault();load(true)}); $('refresh').addEventListener('click',()=>load(false,true)); $('range').addEventListener('change',()=>{syncCustomRange();if($('range').value!=='custom')load(false,true)}); $('model').addEventListener('change',()=>load(false,true)); $('from').addEventListener('change',()=>{syncDatePlaceholder('from');if($('range').value==='custom'&&$('to').value)load(false,true)}); $('to').addEventListener('change',()=>{syncDatePlaceholder('to');if($('range').value==='custom'&&$('from').value)load(false,true)}); document.querySelectorAll('#tokenUnitSwitch [data-token-unit]').forEach(button=>button.addEventListener('click',()=>{tokenUnit=button.dataset.tokenUnit;localStorage.setItem(TOKEN_UNIT_KEY,tokenUnit);syncDisplayControls();refreshDisplayUnits()})); document.querySelectorAll('#currencySwitch [data-currency]').forEach(button=>button.addEventListener('click',()=>{currency=button.dataset.currency;localStorage.setItem(CURRENCY_KEY,currency);syncDisplayControls();refreshDisplayUnits()})); $('usdCnyRate').addEventListener('change',()=>{const next=Number($('usdCnyRate').value);if(Number.isFinite(next)&&next>0){usdCnyRate=next;localStorage.setItem(USD_CNY_RATE_KEY,String(next));refreshDisplayUnits()}else{$('usdCnyRate').value=String(usdCnyRate)}}); document.querySelectorAll('#modelMetric [data-metric]').forEach(button=>button.addEventListener('click',()=>{modelMetric=button.dataset.metric; if(data)renderCharts(data)})); syncDisplayControls(); window.addEventListener('resize',()=>Object.values(charts).forEach(instance=>instance.resize()));
})();
</script>
</body>
</html>`
